"1. Install Go" -> "2. Run unit tests" --\
-> "3. update codecov" -> "4. Import Code-Signing Certificates" --\
-> "5. Install gon via HomeBrew for code signing and app" --\
-> "6. Build and pack" -> "7. code sign and notarize" --> "8. upload release assets"
